services:
  server:
    container_name: cpe-guesser
    image: cpe-guesser:1.0
    build: ..
    volumes:
      - ../data/:/data/:rw
    ports:
      - 8000:8000
    depends_on:
      - valkey
  valkey:
    container_name: cpe-guesser-db
    image: "valkey/valkey:alpine"
